AWSTemplateFormatVersion: '2010-09-09'
Description: OpenVPN Server for GL-iNET Router

Parameters:
  InstanceType:
    Type: String
    Default: t3.micro
    Description: EC2 instance type

Resources:
  VPNSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: OpenVPN Server Security Group
      SecurityGroupIngress:
        - IpProtocol: udp
          FromPort: 1194
          ToPort: 1194
          CidrIp: 0.0.0.0/0
          Description: OpenVPN UDP
      Tags:
        - Key: Name
          Value: OpenVPN-SG

  VPNInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Tags:
        - Key: Name
          Value: OpenVPN-Role

  VPNInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref VPNInstanceRole

  VPNInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Sub '{{resolve:ssm:/aws/service/canonical/ubuntu/server/22.04/stable/current/amd64/hvm/ebs-gp2/ami-id}}'
      InstanceType: !Ref InstanceType
      IamInstanceProfile: !Ref VPNInstanceProfile
      SecurityGroupIds:
        - !Ref VPNSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -e
          export DEBIAN_FRONTEND=noninteractive
          
          apt-get update
          apt-get install -y openvpn easy-rsa iptables-persistent
          
          make-cadir /etc/openvpn/easy-rsa
          cd /etc/openvpn/easy-rsa
          
          cat > vars <<'VARS'
          set_var EASYRSA_REQ_COUNTRY    "US"
          set_var EASYRSA_REQ_PROVINCE   "NY"
          set_var EASYRSA_REQ_CITY       "NYC"
          set_var EASYRSA_REQ_ORG        "VPN"
          set_var EASYRSA_REQ_EMAIL      "admin@vpn.local"
          set_var EASYRSA_REQ_OU         "VPN"
          set_var EASYRSA_ALGO           "ec"
          set_var EASYRSA_DIGEST         "sha512"
          VARS
          
          ./easyrsa --batch init-pki
          ./easyrsa --batch build-ca nopass
          ./easyrsa --batch gen-dh
          ./easyrsa --batch build-server-full server nopass
          ./easyrsa --batch build-client-full client nopass
          openvpn --genkey secret pki/ta.key
          
          cat > /etc/openvpn/server.conf <<'CONF'
          port 1194
          proto udp
          dev tun
          ca /etc/openvpn/easy-rsa/pki/ca.crt
          cert /etc/openvpn/easy-rsa/pki/issued/server.crt
          key /etc/openvpn/easy-rsa/pki/private/server.key
          dh /etc/openvpn/easy-rsa/pki/dh.pem
          tls-auth /etc/openvpn/easy-rsa/pki/ta.key 0
          server 10.8.0.0 255.255.255.0
          push "redirect-gateway def1 bypass-dhcp"
          push "dhcp-option DNS 8.8.8.8"
          push "dhcp-option DNS 8.8.4.4"
          keepalive 10 120
          cipher AES-256-GCM
          user nobody
          group nogroup
          persist-key
          persist-tun
          status /var/log/openvpn-status.log
          verb 3
          CONF
          
          echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
          sysctl -p
          
          IFACE=$(ip route | grep default | awk '{print $5}')
          iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o $IFACE -j MASQUERADE
          netfilter-persistent save
          systemctl enable netfilter-persistent
          
          systemctl enable openvpn@server
          systemctl start openvpn@server
          
          PUBLIC_IP=$$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4)
          cat > /root/client.ovpn <<CLIENT
          client
          dev tun
          proto udp
          remote $$PUBLIC_IP 1194
          resolv-retry infinite
          nobind
          persist-key
          persist-tun
          remote-cert-tls server
          cipher AES-256-GCM
          verb 3
          key-direction 1
          
          <ca>
          $(cat /etc/openvpn/easy-rsa/pki/ca.crt)
          </ca>
          
          <cert>
          $(cat /etc/openvpn/easy-rsa/pki/issued/client.crt)
          </cert>
          
          <key>
          $(cat /etc/openvpn/easy-rsa/pki/private/client.key)
          </key>
          
          <tls-auth>
          $(cat /etc/openvpn/easy-rsa/pki/ta.key)
          </tls-auth>
          CLIENT
          
          chmod 644 /root/client.ovpn
          touch /root/vpn-ready
      Tags:
        - Key: Name
          Value: OpenVPN-Server

Outputs:
  InstanceId:
    Description: EC2 Instance ID
    Value: !Ref VPNInstance
    Export:
      Name: !Sub '${AWS::StackName}-InstanceId'
  
  PublicIP:
    Description: Public IP Address
    Value: !GetAtt VPNInstance.PublicIp
    Export:
      Name: !Sub '${AWS::StackName}-PublicIP'
  
  SecurityGroupId:
    Description: Security Group ID
    Value: !Ref VPNSecurityGroup
    Export:
      Name: !Sub '${AWS::StackName}-SecurityGroupId'
